-- Read-only V011 verification. Run as HOSPITAL_APP after V011.
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN ('ROOMS','BEDS','ADMISSIONS','ADMISSION_TRANSFERS') ORDER BY TABLE_NAME;
SELECT SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME='ADMISSION_NUMBER_SEQ';
SELECT TABLE_NAME,COLUMN_NAME,NULLABLE FROM USER_TAB_COLUMNS WHERE TABLE_NAME IN ('ROOMS','BEDS','ADMISSIONS','ADMISSION_TRANSFERS') ORDER BY TABLE_NAME,COLUMN_ID;
SELECT CONSTRAINT_NAME,TABLE_NAME,CONSTRAINT_TYPE,STATUS FROM USER_CONSTRAINTS WHERE TABLE_NAME IN ('ROOMS','BEDS','ADMISSIONS','ADMISSION_TRANSFERS') ORDER BY TABLE_NAME,CONSTRAINT_NAME;
SELECT INDEX_NAME,TABLE_NAME,STATUS FROM USER_INDEXES WHERE INDEX_NAME IN ('UK_ADM_ACTIVE_PATIENT','UK_ADM_ACTIVE_BED','IDX_ADMISSIONS_DOCTOR','IDX_ADMISSIONS_BED','IDX_ADMISSIONS_STATUS','IDX_ADMISSIONS_DATE','IDX_BEDS_STATUS','IDX_ROOMS_STATUS') ORDER BY INDEX_NAME;
SELECT CONSTRAINT_NAME,TABLE_NAME,R_CONSTRAINT_NAME,STATUS FROM USER_CONSTRAINTS WHERE CONSTRAINT_TYPE='R' AND TABLE_NAME IN ('ROOMS','BEDS','ADMISSIONS','ADMISSION_TRANSFERS') ORDER BY TABLE_NAME,CONSTRAINT_NAME;
