<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${formMode=='EDIT'?'Edit Appointment':'Book Appointment'}</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body>
<%@ include file="/WEB-INF/views/common/header.jsp" %><main class="container py-4"><h1>${formMode=='EDIT'?'Edit Appointment Details':'Book Appointment'}</h1>
<c:if test="${not empty errorMessage}"><div class="alert alert-danger"><c:out value="${errorMessage}"/></div></c:if>
<form method="post" class="card card-body" id="appointmentForm"><input type="hidden" name="csrfToken" value="<c:out value='${sessionScope.csrfToken}'/>"><input type="hidden" name="appointmentId" value="<c:out value='${appointmentForm.appointmentId}'/>">
<c:if test="${formMode!='EDIT'}"><label class="form-label">Patient</label><c:choose><c:when test="${sessionScope.authenticatedUser.roleName=='PATIENT'}"><c:forEach items="${patients}" var="p"><c:if test="${p.userId==sessionScope.authenticatedUser.userId}"><input type="hidden" name="patientId" value="${p.patientId}"><p class="form-control-plaintext"><c:out value="${p.fullName}"/> (<c:out value="${p.patientNumber}"/>)</p></c:if></c:forEach></c:when><c:otherwise><select class="form-select" name="patientId" required><option value="">Select patient</option><c:forEach items="${patients}" var="p"><option value="${p.patientId}" ${appointmentForm.patientId==p.patientId?'selected':''}><c:out value="${p.patientNumber}"/> - <c:out value="${p.fullName}"/></option></c:forEach></select></c:otherwise></c:choose>
<label class="form-label mt-3">Doctor</label><select class="form-select" id="doctorId" name="doctorId" required><option value="">Select doctor</option><c:forEach items="${doctors}" var="d"><option value="${d.doctorId}" ${appointmentForm.doctorId==d.doctorId?'selected':''}><c:out value="${d.fullName}"/> - <c:out value="${d.departmentName}"/></option></c:forEach></select>
<label class="form-label mt-3">Date</label><input class="form-control" id="appointmentDate" type="date" name="appointmentDate" value="<c:out value='${appointmentForm.appointmentDate}'/>" required>
<label class="form-label mt-3">Available time</label><select class="form-select" id="startTime" name="startTime" data-endpoint="${pageContext.request.contextPath}/appointments/slots" data-selected="<c:out value='${appointmentForm.startTime}'/>" required disabled><option value="">Select doctor and date</option></select></c:if>
<label class="form-label mt-3">Reason</label><textarea class="form-control" name="reason" maxlength="500" required><c:out value="${appointmentForm.reason}"/></textarea><label class="form-label mt-3">Notes</label><textarea class="form-control" name="notes" maxlength="1000"><c:out value="${appointmentForm.notes}"/></textarea><div class="mt-3"><button class="btn btn-primary">Save</button> <a class="btn btn-secondary" href="${pageContext.request.contextPath}/appointments">Cancel</a></div></form></main>
<script src="${pageContext.request.contextPath}/assets/js/appointments.js" defer></script><%@ include file="/WEB-INF/views/common/footer.jsp" %></body></html>
