package com.hospital.management.service.impl;
import com.hospital.management.dao.*;import com.hospital.management.dao.impl.*;import com.hospital.management.model.*;import com.hospital.management.service.*;import com.hospital.management.validation.*;import org.slf4j.*;import java.sql.SQLException;import java.util.*;
public class DepartmentServiceImpl implements DepartmentService{private static final Logger LOG=LoggerFactory.getLogger(DepartmentServiceImpl.class);private final DepartmentDao dao;private final DepartmentValidator validator;private final AuditLogDao audit;public DepartmentServiceImpl(){this(new DepartmentDaoImpl(),new DepartmentValidator(),new AuditLogDaoImpl());}public DepartmentServiceImpl(DepartmentDao d,DepartmentValidator v,AuditLogDao a){dao=d;validator=v;audit=a;}
 public Page<Department> listDepartments(PageRequest r){try{return dao.findAll(r);}catch(SQLException e){LOG.error("Department listing failed",e);return new Page<>(List.of(),r.getPageNumber(),r.getPageSize(),0);}}public Optional<Department> getDepartment(Long id){try{return dao.findById(id);}catch(SQLException e){LOG.error("Department lookup failed",e);return Optional.empty();}}
 public ServiceResult<Long> createDepartment(Department d,AuditContext a){normalize(d);ValidationResult v=validator.validate(d);if(v.hasErrors())return ServiceResult.failure(ServiceResult.Status.VALIDATION_ERROR,"Please correct the highlighted fields",v.getErrors());try{if(dao.existsByName(d.getDepartmentName()))return duplicate();long id=dao.create(d);event("DEPARTMENT_CREATED",id,a);return ServiceResult.success("Department created",id);}catch(SQLException e){LOG.error("Department creation failed",e);return system();}}
 public ServiceResult<Void> updateDepartment(Department d,AuditContext a){normalize(d);ValidationResult v=validator.validate(d);if(v.hasErrors())return ServiceResult.failure(ServiceResult.Status.VALIDATION_ERROR,"Please correct the highlighted fields",v.getErrors());try{if(d.getDepartmentId()==null||dao.findById(d.getDepartmentId()).isEmpty())return fail(ServiceResult.Status.NOT_FOUND,"Department not found");if(dao.existsByNameExcludingId(d.getDepartmentName(),d.getDepartmentId()))return ServiceResult.failure(ServiceResult.Status.DUPLICATE,"A department with this name already exists",Map.of("departmentName","Department name already exists"));dao.update(d);event("DEPARTMENT_UPDATED",d.getDepartmentId(),a);return ServiceResult.success("Department updated",null);}catch(SQLException e){LOG.error("Department update failed",e);return system();}}
 public ServiceResult<Void> activateDepartment(Long id,AuditContext a){return status(id,"ACTIVE","DEPARTMENT_ACTIVATED",a);}public ServiceResult<Void> deactivateDepartment(Long id,AuditContext a){try{if(dao.findById(id).isEmpty())return fail(ServiceResult.Status.NOT_FOUND,"Department not found");if(dao.hasActiveDoctors(id))return fail(ServiceResult.Status.CONFLICT,"Department cannot be deactivated while active doctors are assigned");return status(id,"INACTIVE","DEPARTMENT_DEACTIVATED",a);}catch(SQLException e){LOG.error("Department deactivation failed",e);return system();}}
 private ServiceResult<Void> status(Long id,String s,String event,AuditContext a){try{if(dao.findById(id).isEmpty())return fail(ServiceResult.Status.NOT_FOUND,"Department not found");dao.updateStatus(id,s);event(event,id,a);return ServiceResult.success("Department status updated",null);}catch(SQLException e){LOG.error("Department status update failed",e);return system();}}
 private void event(String e,Long id,AuditContext a){try{audit.recordEvent(e,a.userId(),"DEPARTMENT",id,a.ipAddress(),a.userAgent());}catch(RuntimeException ex){LOG.warn("Department audit event failed: {}",e,ex);}}private void normalize(Department d){d.setDepartmentName(trim(d.getDepartmentName()));d.setDescription(trim(d.getDescription()));d.setLocation(trim(d.getLocation()));d.setStatus(d.getStatus()==null?null:d.getStatus().trim().toUpperCase(Locale.ROOT));}private String trim(String s){return s==null?null:s.trim();}private<T>ServiceResult<T> fail(ServiceResult.Status s,String m){return ServiceResult.failure(s,m,Map.of());}private<T>ServiceResult<T> system(){return fail(ServiceResult.Status.SYSTEM_ERROR,"Department service is temporarily unavailable");}private ServiceResult<Long> duplicate(){return ServiceResult.failure(ServiceResult.Status.DUPLICATE,"A department with this name already exists",Map.of("departmentName","Department name already exists"));}}
