package com.hospital.management.controller.report;
import com.hospital.management.dao.AuditLogDao;import com.hospital.management.model.report.*;import com.hospital.management.service.ReportService;import org.junit.jupiter.api.Test;import javax.servlet.RequestDispatcher;import javax.servlet.http.*;import java.io.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class ReportServletTest{
 private HttpServletRequest request(RequestDispatcher d){HttpServletRequest q=mock(HttpServletRequest.class);when(q.getRequestDispatcher(anyString())).thenReturn(d);return q;}
 @Test void dashboardSetsExpectedAttributesAndForwards()throws Exception{ReportService s=mock(ReportService.class);when(s.getHospitalOverview(any())).thenReturn(HospitalOverviewReport.empty());when(s.getAppointmentStatusSummary(any())).thenReturn(List.of());when(s.getDoctorDepartmentSummary(any())).thenReturn(List.of());when(s.getAdmissionStatusSummary(any())).thenReturn(List.of());when(s.getBedOccupancySummary(any())).thenReturn(List.of());when(s.getBillingStatusSummary(any())).thenReturn(List.of());RequestDispatcher d=mock(RequestDispatcher.class);HttpServletRequest q=request(d);new ReportDashboardServlet(s).doGet(q,mock(HttpServletResponse.class));verify(q).setAttribute(eq("overview"),any());verify(d).forward(eq(q),any());}
 @Test void specializedReportHandlesEmptyData()throws Exception{ReportService s=mock(ReportService.class);when(s.getPatientRegistrationTrend(any())).thenReturn(List.of());when(s.getPatientStatusSummary(any())).thenReturn(List.of());RequestDispatcher d=mock(RequestDispatcher.class);HttpServletRequest q=request(d);new PatientReportServlet(s).doGet(q,mock(HttpServletResponse.class));verify(q).setAttribute("trend",List.of());verify(q).setAttribute("statusSummary",List.of());verify(d).forward(eq(q),any());}
 @Test void exportRejectsUnknownType()throws Exception{HttpServletRequest q=mock(HttpServletRequest.class);HttpServletResponse r=mock(HttpServletResponse.class);when(q.getParameter("type")).thenReturn("passwords");new ReportExportServlet(mock(ReportService.class),mock(AuditLogDao.class)).doGet(q,r);verify(r).sendError(400);}
 @Test void exportIsCsvAndAudited()throws Exception{ReportService s=mock(ReportService.class);when(s.getAppointmentStatusSummary(any())).thenReturn(List.of(new AppointmentStatusSummary("COMPLETED",2)));AuditLogDao audit=mock(AuditLogDao.class);HttpServletRequest q=mock(HttpServletRequest.class);HttpServletResponse r=mock(HttpServletResponse.class);HttpSession session=mock(HttpSession.class);StringWriter text=new StringWriter();when(q.getParameter("type")).thenReturn("appointments");when(q.getParameter("dateFrom")).thenReturn("2026-07-01");when(q.getParameter("dateTo")).thenReturn("2026-07-23");when(q.getSession(false)).thenReturn(session);when(r.getWriter()).thenReturn(new PrintWriter(text));new ReportExportServlet(s,audit).doGet(q,r);assertTrue(text.toString().contains("COMPLETED,2"));verify(r).setContentType("text/csv; charset=UTF-8");verify(audit).recordEvent(eq("REPORT_EXPORTED"),isNull(),eq("REPORT"),eq(1L),any(),any());}
}
