-- Run as HOSPITAL_APP after schema.sql and seed-data.sql.
-- Replace every REPLACE_WITH_BCRYPT_HASH value with a hash generated locally.
-- Never place plaintext passwords in this file or commit known demo credentials.

MERGE INTO USERS u USING (SELECT 'demo_admin' USERNAME, 'admin@example.invalid' EMAIL, 'ADMIN' ROLE_NAME FROM DUAL) s
ON (UPPER(u.USERNAME)=UPPER(s.USERNAME)) WHEN NOT MATCHED THEN INSERT (USERNAME,PASSWORD_HASH,EMAIL,ROLE_ID,STATUS)
VALUES(s.USERNAME,'REPLACE_WITH_BCRYPT_HASH',s.EMAIL,(SELECT ROLE_ID FROM ROLES WHERE ROLE_NAME=s.ROLE_NAME),'ACTIVE');
MERGE INTO USERS u USING (SELECT 'demo_doctor' USERNAME, 'doctor@example.invalid' EMAIL, 'DOCTOR' ROLE_NAME FROM DUAL) s
ON (UPPER(u.USERNAME)=UPPER(s.USERNAME)) WHEN NOT MATCHED THEN INSERT (USERNAME,PASSWORD_HASH,EMAIL,ROLE_ID,STATUS)
VALUES(s.USERNAME,'REPLACE_WITH_BCRYPT_HASH',s.EMAIL,(SELECT ROLE_ID FROM ROLES WHERE ROLE_NAME=s.ROLE_NAME),'ACTIVE');
MERGE INTO USERS u USING (SELECT 'demo_patient' USERNAME, 'patient@example.invalid' EMAIL, 'PATIENT' ROLE_NAME FROM DUAL) s
ON (UPPER(u.USERNAME)=UPPER(s.USERNAME)) WHEN NOT MATCHED THEN INSERT (USERNAME,PASSWORD_HASH,EMAIL,ROLE_ID,STATUS)
VALUES(s.USERNAME,'REPLACE_WITH_BCRYPT_HASH',s.EMAIL,(SELECT ROLE_ID FROM ROLES WHERE ROLE_NAME=s.ROLE_NAME),'ACTIVE');
COMMIT;
