-- Run this script while connected to XEPDB1 as an Oracle administrative user.
-- IMPORTANT: Replace CHANGE_THIS_PASSWORD with a strong local password before execution.
-- Never commit the chosen password to version control.

CREATE USER HOSPITAL_APP IDENTIFIED BY CHANGE_THIS_PASSWORD
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA 100M ON USERS;

GRANT CREATE SESSION TO HOSPITAL_APP;
GRANT CREATE TABLE TO HOSPITAL_APP;
GRANT CREATE VIEW TO HOSPITAL_APP;
GRANT CREATE SEQUENCE TO HOSPITAL_APP;
GRANT CREATE TRIGGER TO HOSPITAL_APP;
