package com.hospital.management.dao.impl;
import com.hospital.management.dao.AppointmentDao;import com.hospital.management.model.*;import com.hospital.management.util.DatabaseConnectionManager;import java.sql.*;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.ArrayList;import java.util.List;import java.util.Locale;import java.util.Optional;
/** Oracle appointment persistence using bound parameters only. */
public class AppointmentDaoImpl implements AppointmentDao {private static final DateTimeFormatter T=DateTimeFormatter.ofPattern("HH:mm");private static final String SELECT="SELECT a.*,p.PATIENT_NUMBER,p.FIRST_NAME||' '||p.LAST_NAME PATIENT_NAME,d.FIRST_NAME||' '||d.LAST_NAME DOCTOR_NAME,d.DEPARTMENT_ID,dep.DEPARTMENT_NAME,u.USERNAME CREATED_BY_USERNAME FROM APPOINTMENTS a JOIN PATIENTS p ON p.PATIENT_ID=a.PATIENT_ID JOIN DOCTORS d ON d.DOCTOR_ID=a.DOCTOR_ID JOIN DEPARTMENTS dep ON dep.DEPARTMENT_ID=d.DEPARTMENT_ID LEFT JOIN USERS u ON u.USER_ID=a.CREATED_BY ";
public Optional<Appointment> findById(Long id)throws SQLException{if(id==null)return Optional.empty();try(Connection c=DatabaseConnectionManager.getConnection();PreparedStatement s=c.prepareStatement(SELECT+"WHERE a.APPOINTMENT_ID=?")){s.setLong(1,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(map(r)):Optional.empty();}}}
public Page<Appointment> findAll(PageRequest p,Long pi,Long di,Long dep,LocalDate f,LocalDate t,String st)throws SQLException{String w=where();try(Connection c=DatabaseConnectionManager.getConnection();PreparedStatement s=c.prepareStatement(SELECT+w+" ORDER BY a.APPOINTMENT_DATE DESC,a.START_TIME ASC,a.APPOINTMENT_ID DESC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY")){int i=bind(s,p.getSearchTerm(),pi,di,dep,f,t,st);s.setInt(i++,p.getOffset());s.setInt(i,p.getPageSize());List<Appointment>x=new ArrayList<>();try(ResultSet r=s.executeQuery()){while(r.next())x.add(map(r));}return new Page<>(x,p.getPageNumber(),p.getPageSize(),count(p.getSearchTerm(),pi,di,dep,f,t,st));}}
public long count(String q,Long pi,Long di,Long dep,LocalDate f,LocalDate t,String st)throws SQLException{try(Connection c=DatabaseConnectionManager.getConnection();PreparedStatement s=c.prepareStatement("SELECT COUNT(1) FROM APPOINTMENTS a JOIN PATIENTS p ON p.PATIENT_ID=a.PATIENT_ID JOIN DOCTORS d ON d.DOCTOR_ID=a.DOCTOR_ID JOIN DEPARTMENTS dep ON dep.DEPARTMENT_ID=d.DEPARTMENT_ID "+where())){bind(s,q,pi,di,dep,f,t,st);try(ResultSet r=s.executeQuery()){r.next();return r.getLong(1);}}}
private String where(){return "WHERE (? IS NULL OR UPPER(p.PATIENT_NUMBER||' '||p.FIRST_NAME||' '||p.LAST_NAME||' '||d.FIRST_NAME||' '||d.LAST_NAME||' '||d.REGISTRATION_NUMBER||' '||dep.DEPARTMENT_NAME||' '||a.REASON||' '||a.STATUS) LIKE ? ESCAPE '\\') AND (? IS NULL OR a.PATIENT_ID=?) AND (? IS NULL OR a.DOCTOR_ID=?) AND (? IS NULL OR d.DEPARTMENT_ID=?) AND (? IS NULL OR a.APPOINTMENT_DATE>=?) AND (? IS NULL OR a.APPOINTMENT_DATE<?) AND (? IS NULL OR a.STATUS=?) ";}
private int bind(PreparedStatement s,String q,Long pi,Long di,Long dep,LocalDate f,LocalDate t,String st)throws SQLException{String term=q==null||q.isBlank()?null:"%"+q.trim().toUpperCase().replace("\\","\\\\").replace("%","\\%").replace("_","\\_")+"%";int i=1;s.setString(i++,term);s.setString(i++,term);i=pair(s,i,pi);i=pair(s,i,di);i=pair(s,i,dep);i=datePair(s,i,f);i=datePair(s,i,t==null?null:t.plusDays(1));String status=st==null||st.isBlank()?null:st.toUpperCase(Locale.ROOT);s.setString(i++,status);s.setString(i++,status);return i;}
private int pair(PreparedStatement s,int i,Long v)throws SQLException{if(v==null){s.setNull(i++,Types.NUMERIC);s.setNull(i++,Types.NUMERIC);}else{s.setLong(i++,v);s.setLong(i++,v);}return i;}private int datePair(PreparedStatement s,int i,LocalDate v)throws SQLException{if(v==null){s.setNull(i++,Types.DATE);s.setNull(i++,Types.DATE);}else{s.setDate(i++,Date.valueOf(v));s.setDate(i++,Date.valueOf(v));}return i;}
public long create(Connection c,Appointment a)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO APPOINTMENTS(PATIENT_ID,DOCTOR_ID,APPOINTMENT_DATE,START_TIME,END_TIME,REASON,STATUS,NOTES,CREATED_BY) VALUES(?,?,?,?,?,?,?,?,?)",new String[]{"APPOINTMENT_ID"})){s.setLong(1,a.getPatientId());s.setLong(2,a.getDoctorId());s.setDate(3,Date.valueOf(a.getAppointmentDate()));s.setString(4,T.format(a.getStartTime()));s.setString(5,T.format(a.getEndTime()));s.setString(6,a.getReason());s.setString(7,a.getStatus());s.setString(8,a.getNotes());s.setLong(9,a.getCreatedBy());s.executeUpdate();try(ResultSet r=s.getGeneratedKeys()){if(r.next())return r.getLong(1);}throw new SQLException("No appointment identifier returned");}}
public boolean updateDetails(Connection c,Appointment a)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE APPOINTMENTS SET REASON=?,NOTES=?,UPDATED_AT=CURRENT_TIMESTAMP WHERE APPOINTMENT_ID=?")){s.setString(1,a.getReason());s.setString(2,a.getNotes());s.setLong(3,a.getAppointmentId());return s.executeUpdate()==1;}}
public boolean reschedule(Connection c,Long id,LocalDate d,LocalTime a,LocalTime b,String reason,String notes)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE APPOINTMENTS SET APPOINTMENT_DATE=?,START_TIME=?,END_TIME=?,REASON=?,NOTES=?,UPDATED_AT=CURRENT_TIMESTAMP WHERE APPOINTMENT_ID=?")){s.setDate(1,Date.valueOf(d));s.setString(2,T.format(a));s.setString(3,T.format(b));s.setString(4,reason);s.setString(5,notes);s.setLong(6,id);return s.executeUpdate()==1;}}
public boolean updateStatus(Connection c,Long id,String st)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE APPOINTMENTS SET STATUS=?,UPDATED_AT=CURRENT_TIMESTAMP WHERE APPOINTMENT_ID=?")){s.setString(1,st);s.setLong(2,id);return s.executeUpdate()==1;}}
public boolean existsDoctorBooking(Long d,LocalDate day,LocalTime start,Long ex)throws SQLException{return exists("SELECT 1 FROM APPOINTMENTS WHERE DOCTOR_ID=? AND APPOINTMENT_DATE>=? AND APPOINTMENT_DATE<? AND START_TIME=? AND STATUS IN('SCHEDULED','CONFIRMED') AND (? IS NULL OR APPOINTMENT_ID<>?) FETCH FIRST 1 ROW ONLY",d,day,T.format(start),null,null,ex);}
public boolean existsPatientOverlap(Long p,LocalDate day,LocalTime start,LocalTime end,Long ex)throws SQLException{return exists("SELECT 1 FROM APPOINTMENTS WHERE PATIENT_ID=? AND APPOINTMENT_DATE>=? AND APPOINTMENT_DATE<? AND START_TIME<? AND END_TIME>? AND STATUS IN('SCHEDULED','CONFIRMED') AND (? IS NULL OR APPOINTMENT_ID<>?) FETCH FIRST 1 ROW ONLY",p,day,T.format(end),T.format(start),null,ex);}
private boolean exists(String sql,Long id,LocalDate day,String x,String y,String z,Long ex)throws SQLException{try(Connection c=DatabaseConnectionManager.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,id);s.setDate(2,Date.valueOf(day));s.setDate(3,Date.valueOf(day.plusDays(1)));s.setString(4,x);int i=5;if(y!=null)s.setString(i++,y);if(ex==null){s.setNull(i++,Types.NUMERIC);s.setNull(i,Types.NUMERIC);}else{s.setLong(i++,ex);s.setLong(i,ex);}try(ResultSet r=s.executeQuery()){return r.next();}}}
public List<LocalTime> findBookedStartTimes(Long d,LocalDate day)throws SQLException{try(Connection c=DatabaseConnectionManager.getConnection();PreparedStatement s=c.prepareStatement("SELECT START_TIME FROM APPOINTMENTS WHERE DOCTOR_ID=? AND APPOINTMENT_DATE>=? AND APPOINTMENT_DATE<? AND STATUS IN('SCHEDULED','CONFIRMED') ORDER BY START_TIME")){s.setLong(1,d);s.setDate(2,Date.valueOf(day));s.setDate(3,Date.valueOf(day.plusDays(1)));List<LocalTime>x=new ArrayList<>();try(ResultSet r=s.executeQuery()){while(r.next())x.add(LocalTime.parse(r.getString(1),T));}return x;}}
private Appointment map(ResultSet r)throws SQLException{Appointment a=new Appointment();a.setAppointmentId(r.getLong("APPOINTMENT_ID"));a.setPatientId(r.getLong("PATIENT_ID"));a.setPatientNumber(r.getString("PATIENT_NUMBER"));a.setPatientName(r.getString("PATIENT_NAME"));a.setDoctorId(r.getLong("DOCTOR_ID"));a.setDoctorName(r.getString("DOCTOR_NAME"));a.setDepartmentId(r.getLong("DEPARTMENT_ID"));a.setDepartmentName(r.getString("DEPARTMENT_NAME"));a.setAppointmentDate(r.getDate("APPOINTMENT_DATE").toLocalDate());a.setStartTime(LocalTime.parse(r.getString("START_TIME"),T));a.setEndTime(LocalTime.parse(r.getString("END_TIME"),T));a.setReason(r.getString("REASON"));a.setStatus(r.getString("STATUS"));a.setNotes(r.getString("NOTES"));a.setCreatedBy(r.getLong("CREATED_BY"));a.setCreatedByUsername(r.getString("CREATED_BY_USERNAME"));Timestamp c=r.getTimestamp("CREATED_AT"),u=r.getTimestamp("UPDATED_AT");a.setCreatedAt(c==null?null:c.toLocalDateTime());a.setUpdatedAt(u==null?null:u.toLocalDateTime());return a;}}
