package com.hospital.management.dao.impl;
import com.hospital.management.dao.DepartmentDao;import com.hospital.management.model.*;import com.hospital.management.util.DatabaseConnectionManager;import java.sql.*;import java.util.*;
public class DepartmentDaoImpl implements DepartmentDao{private static final String COLS="DEPARTMENT_ID,DEPARTMENT_NAME,DESCRIPTION,LOCATION,STATUS,CREATED_AT,UPDATED_AT";
 public Optional<Department> findById(Long id)throws SQLException{return one("SELECT "+COLS+" FROM DEPARTMENTS WHERE DEPARTMENT_ID=?",id);}public Optional<Department> findByName(String n)throws SQLException{return one("SELECT "+COLS+" FROM DEPARTMENTS WHERE UPPER(DEPARTMENT_NAME)=UPPER(?)",n);}private Optional<Department> one(String sql,Object v)throws SQLException{try(Connection c=DatabaseConnectionManager.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setObject(1,v);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(map(r)):Optional.empty();}}}
 public Page<Department> findAll(PageRequest q)throws SQLException{String sql="SELECT "+COLS+" FROM DEPARTMENTS WHERE (? IS NULL OR UPPER(DEPARTMENT_NAME) LIKE ? ESCAPE '\\' OR UPPER(DESCRIPTION) LIKE ? ESCAPE '\\' OR UPPER(LOCATION) LIKE ? ESCAPE '\\' OR UPPER(STATUS) LIKE ? ESCAPE '\\') ORDER BY DEPARTMENT_NAME OFFSET ? ROWS FETCH NEXT ? ROWS ONLY";String like=pattern(q.getSearchTerm()),flag=q.getSearchTerm().isEmpty()?null:like;List<Department> list=new ArrayList<>();try(Connection c=DatabaseConnectionManager.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setString(1,flag);for(int i=2;i<=5;i++)p.setString(i,like);p.setInt(6,q.getOffset());p.setInt(7,q.getPageSize());try(ResultSet r=p.executeQuery()){while(r.next())list.add(map(r));}}return new Page<>(list,q.getPageNumber(),q.getPageSize(),count(q.getSearchTerm()));}
 public long count(String s)throws SQLException{String sql="SELECT COUNT(*) FROM DEPARTMENTS WHERE (? IS NULL OR UPPER(DEPARTMENT_NAME) LIKE ? ESCAPE '\\' OR UPPER(DESCRIPTION) LIKE ? ESCAPE '\\' OR UPPER(LOCATION) LIKE ? ESCAPE '\\' OR UPPER(STATUS) LIKE ? ESCAPE '\\')";String like=pattern(s),flag=s==null||s.isBlank()?null:like;try(Connection c=DatabaseConnectionManager.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setString(1,flag);for(int i=2;i<=5;i++)p.setString(i,like);try(ResultSet r=p.executeQuery()){r.next();return r.getLong(1);}}}
 public long create(Department d)throws SQLException{try(Connection c=DatabaseConnectionManager.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO DEPARTMENTS(DEPARTMENT_NAME,DESCRIPTION,LOCATION,STATUS) VALUES(?,?,?,?)",new String[]{"DEPARTMENT_ID"})){bind(p,d);p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){if(r.next())return r.getLong(1);}throw new SQLException("No generated department ID");}}
 public boolean update(Department d)throws SQLException{try(Connection c=DatabaseConnectionManager.getConnection();PreparedStatement p=c.prepareStatement("UPDATE DEPARTMENTS SET DEPARTMENT_NAME=?,DESCRIPTION=?,LOCATION=?,STATUS=?,UPDATED_AT=CURRENT_TIMESTAMP WHERE DEPARTMENT_ID=?")){bind(p,d);p.setLong(5,d.getDepartmentId());return p.executeUpdate()==1;}}
 public boolean updateStatus(Long id,String s)throws SQLException{try(Connection c=DatabaseConnectionManager.getConnection();PreparedStatement p=c.prepareStatement("UPDATE DEPARTMENTS SET STATUS=?,UPDATED_AT=CURRENT_TIMESTAMP WHERE DEPARTMENT_ID=?")){p.setString(1,s);p.setLong(2,id);return p.executeUpdate()==1;}}
 public boolean existsByName(String n)throws SQLException{return exists("SELECT 1 FROM DEPARTMENTS WHERE UPPER(DEPARTMENT_NAME)=UPPER(?)",n,null);}public boolean existsByNameExcludingId(String n,Long id)throws SQLException{return exists("SELECT 1 FROM DEPARTMENTS WHERE UPPER(DEPARTMENT_NAME)=UPPER(?) AND DEPARTMENT_ID<>?",n,id);}private boolean exists(String sql,String n,Long id)throws SQLException{try(Connection c=DatabaseConnectionManager.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setString(1,n);if(id!=null)p.setLong(2,id);try(ResultSet r=p.executeQuery()){return r.next();}}}
 public boolean hasActiveDoctors(Long id)throws SQLException{try(Connection c=DatabaseConnectionManager.getConnection();PreparedStatement p=c.prepareStatement("SELECT 1 FROM DOCTORS WHERE DEPARTMENT_ID=? AND STATUS='ACTIVE' FETCH FIRST 1 ROW ONLY")){p.setLong(1,id);try(ResultSet r=p.executeQuery()){return r.next();}}}
 private void bind(PreparedStatement p,Department d)throws SQLException{p.setString(1,d.getDepartmentName());p.setString(2,d.getDescription());p.setString(3,d.getLocation());p.setString(4,d.getStatus());}private String pattern(String s){String v=s==null?"":s.trim().toUpperCase(Locale.ROOT).replace("\\","\\\\").replace("%","\\%").replace("_","\\_");return"%"+v+"%";}private Department map(ResultSet r)throws SQLException{Department d=new Department(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5));Timestamp c=r.getTimestamp(6),u=r.getTimestamp(7);d.setCreatedAt(c==null?null:c.toLocalDateTime());d.setUpdatedAt(u==null?null:u.toLocalDateTime());return d;}}
