-- Appointment Management migration for Oracle XE 21c.
-- Allows a cancelled/completed/no-show slot to be booked again while preventing
-- concurrent active bookings for the same doctor, date and start time.
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE APPOINTMENTS DROP CONSTRAINT UK_APPT_DOCTOR_SLOT';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

CREATE UNIQUE INDEX UK_APPT_ACTIVE_DOCTOR_SLOT ON APPOINTMENTS (
    CASE WHEN STATUS IN ('SCHEDULED', 'CONFIRMED') THEN DOCTOR_ID END,
    CASE WHEN STATUS IN ('SCHEDULED', 'CONFIRMED') THEN APPOINTMENT_DATE END,
    CASE WHEN STATUS IN ('SCHEDULED', 'CONFIRMED') THEN START_TIME END
);
CREATE INDEX IDX_APPT_PATIENT_DATE ON APPOINTMENTS (PATIENT_ID, APPOINTMENT_DATE);
CREATE INDEX IDX_APPT_STATUS ON APPOINTMENTS (STATUS);
CREATE INDEX IDX_APPT_CREATED_BY ON APPOINTMENTS (CREATED_BY);
