-- Prescription Management migration. Run once as HOSPITAL_APP.
-- Review and resolve any duplicate non-null MEDICAL_RECORD_ID values first.
ALTER TABLE PRESCRIPTIONS ADD CONSTRAINT UK_RX_MED_REC UNIQUE (MEDICAL_RECORD_ID);
CREATE INDEX IDX_RX_PATIENT ON PRESCRIPTIONS (PATIENT_ID);
CREATE INDEX IDX_RX_DOCTOR ON PRESCRIPTIONS (DOCTOR_ID);
CREATE INDEX IDX_RX_MED_REC ON PRESCRIPTIONS (MEDICAL_RECORD_ID);
CREATE INDEX IDX_RX_DATE ON PRESCRIPTIONS (PRESCRIPTION_DATE);
CREATE INDEX IDX_RX_STATUS ON PRESCRIPTIONS (STATUS);
