-- Billing and Payments migration. Run once as HOSPITAL_APP after V009.
CREATE SEQUENCE BILL_NUMBER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PAYMENT_NUMBER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE INDEX IDX_BILLS_APPT ON BILLS (APPOINTMENT_ID);
CREATE INDEX IDX_BILLS_DATE ON BILLS (BILL_DATE);
CREATE INDEX IDX_PAYMENTS_DATE ON PAYMENTS (PAYMENT_DATE);
CREATE INDEX IDX_PAYMENTS_STATUS ON PAYMENTS (STATUS);
