package com.hospital.management.dao.impl;
import com.hospital.management.model.report.*;import org.junit.jupiter.api.*;import java.math.BigDecimal;import java.sql.*;import java.time.LocalDate;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class ReportDaoImplTest{
 private Connection c;private PreparedStatement p;private ResultSet r;private ReportDaoImpl dao;private ReportFilter f;
 @BeforeEach void setup()throws Exception{c=mock(Connection.class);p=mock(PreparedStatement.class);r=mock(ResultSet.class);when(c.prepareStatement(anyString())).thenReturn(p);when(p.executeQuery()).thenReturn(r);dao=new ReportDaoImpl(){protected Connection connection(){return c;}};f=new ReportFilter(LocalDate.of(2026,7,1),LocalDate.of(2026,7,23),2L,3L,null,null,null,null);}
 @Test void overviewMapsNullMoneyToZero()throws Exception{when(r.next()).thenReturn(true);for(int i=1;i<=7;i++)when(r.getLong(i)).thenReturn((long)i);when(r.getBigDecimal(anyInt())).thenReturn(null);var x=dao.getHospitalOverview(f);assertEquals(1,x.getTotalDepartments());assertEquals(new BigDecimal("0.00"),x.getTotalBilledAmount());verify(p,atLeastOnce()).setDate(anyInt(),any(Date.class));}
 @Test void appointmentStatusMapsAndBindsFilters()throws Exception{when(r.next()).thenReturn(true,false);when(r.getString(1)).thenReturn("COMPLETED");when(r.getLong(2)).thenReturn(4L);var x=dao.getAppointmentStatusSummary(f);assertEquals(1,x.size());assertEquals(4,x.get(0).getAppointmentCount());verify(p).setLong(3,2L);verify(p).setLong(5,3L);}
 @Test void appointmentTrendMaps()throws Exception{when(r.next()).thenReturn(true,false);when(r.getDate(1)).thenReturn(Date.valueOf("2026-07-03"));when(r.getLong(2)).thenReturn(5L);assertEquals(LocalDate.of(2026,7,3),dao.getAppointmentTrend(f).get(0).getReportDate());}
 @Test void patientTrendEmptyIsSafe()throws Exception{when(r.next()).thenReturn(false);assertTrue(dao.getPatientRegistrationTrend(f).isEmpty());}
 @Test void patientStatusMaps()throws Exception{when(r.next()).thenReturn(true,false);when(r.getString(1)).thenReturn("ACTIVE");when(r.getLong(2)).thenReturn(8L);assertEquals(8,dao.getPatientStatusSummary(f).get(0).getPatientCount());}
 @Test void doctorDepartmentMaps()throws Exception{when(r.next()).thenReturn(true,false);when(r.getLong(1)).thenReturn(2L);when(r.getString(2)).thenReturn("Cardiology");when(r.getLong(3)).thenReturn(3L);when(r.getLong(4)).thenReturn(2L);when(r.getLong(5)).thenReturn(7L);assertEquals("Cardiology",dao.getDoctorDepartmentSummary(f).get(0).getDepartmentName());}
 @Test void admissionAndBillingMap()throws Exception{when(r.next()).thenReturn(true,false);when(r.getString(1)).thenReturn("ADMITTED");when(r.getLong(2)).thenReturn(2L);assertEquals(2,dao.getAdmissionStatusSummary(f).get(0).getAdmissionCount());reset(r);when(p.executeQuery()).thenReturn(r);when(r.next()).thenReturn(true,false);when(r.getString(1)).thenReturn("PAID");when(r.getLong(2)).thenReturn(1L);when(r.getBigDecimal(anyInt())).thenReturn(BigDecimal.TEN);assertEquals(new BigDecimal("10.00"),dao.getBillingStatusSummary(f).get(0).getTotalAmount());}
 @Test void occupancyAndRevenueMap()throws Exception{when(r.next()).thenReturn(true,false);when(r.getString(1)).thenReturn("GENERAL");when(r.getLong(2)).thenReturn(10L);when(r.getLong(3)).thenReturn(5L);when(r.getLong(4)).thenReturn(4L);when(r.getLong(5)).thenReturn(1L);when(r.getBigDecimal(6)).thenReturn(new BigDecimal("40"));assertEquals(new BigDecimal("40.00"),dao.getBedOccupancySummary(f).get(0).getOccupancyPercentage());reset(r);when(p.executeQuery()).thenReturn(r);when(r.next()).thenReturn(true,false);when(r.getDate(1)).thenReturn(Date.valueOf("2026-07-03"));when(r.getBigDecimal(anyInt())).thenReturn(BigDecimal.ONE);assertEquals(new BigDecimal("1.00"),dao.getRevenueTrend(f).get(0).getPaidAmount());}
 @Test void sqlIsSelectOnly()throws Exception{when(r.next()).thenReturn(false);dao.getAppointmentTrend(f);verify(c).prepareStatement(argThat(sql->sql.trim().toUpperCase().startsWith("SELECT")));verify(c,never()).prepareStatement(argThat(sql->sql.toUpperCase().matches(".*\\b(INSERT|UPDATE|DELETE|MERGE)\\b.*")));}
}
