package com.hospital.management.service.impl;
import com.hospital.management.dao.*;import com.hospital.management.model.User;import com.hospital.management.service.AuthenticationResult;import com.hospital.management.util.PasswordUtil;import org.junit.jupiter.api.*;import java.sql.SQLException;import java.util.Optional;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class AuthenticationServiceImplTest {UserDao dao;AuditLogDao audit;AuthenticationServiceImpl service;@BeforeEach void setUp(){dao=mock(UserDao.class);audit=mock(AuditLogDao.class);service=new AuthenticationServiceImpl(dao,audit);}
 private User user(){User u=new User();u.setUserId(1L);u.setUsername("alex");u.setEmail("a@example.invalid");u.setRoleName("ADMIN");u.setStatus("ACTIVE");u.setPasswordHash(PasswordUtil.hashPassword("test input"));return u;}
 @Test void success()throws Exception{User u=user();when(dao.findByUsername("alex")).thenReturn(Optional.of(u));AuthenticationResult r=service.authenticate(" alex ","test input");assertEquals(AuthenticationResult.Status.SUCCESS,r.getStatus());verify(dao).updateSuccessfulLogin(1L);}
 @Test void unknownIsGeneric()throws Exception{when(dao.findByUsername("none")).thenReturn(Optional.empty());assertEquals(AuthenticationResult.Status.INVALID_CREDENTIALS,service.authenticate("none","x").getStatus());}
 @Test void inactive()throws Exception{User u=user();u.setStatus("INACTIVE");when(dao.findByUsername("alex")).thenReturn(Optional.of(u));assertEquals(AuthenticationResult.Status.ACCOUNT_INACTIVE,service.authenticate("alex","x").getStatus());}
 @Test void locked()throws Exception{User u=user();u.setStatus("LOCKED");when(dao.findByUsername("alex")).thenReturn(Optional.of(u));assertEquals(AuthenticationResult.Status.ACCOUNT_LOCKED,service.authenticate("alex","x").getStatus());}
 @Test void incrementsFailure()throws Exception{User u=user();when(dao.findByUsername("alex")).thenReturn(Optional.of(u));service.authenticate("alex","wrong");verify(dao).incrementFailedLoginAttempts(1L);}
 @Test void locksAtThreshold()throws Exception{User u=user();u.setFailedLoginAttempts(4);when(dao.findByUsername("alex")).thenReturn(Optional.of(u));service.authenticate("alex","wrong");verify(dao).lockUser(1L);}
 @Test void sqlFailureIsSafe()throws Exception{when(dao.findByUsername("alex")).thenThrow(new SQLException("secret detail"));AuthenticationResult r=service.authenticate("alex","x");assertEquals(AuthenticationResult.Status.SYSTEM_ERROR,r.getStatus());assertFalse(r.getMessage().contains("secret"));}}
